name: Build and Publish Standard Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6  # Upgraded version to clean up warnings
        with:
          context: .
          push: true
          # The line below forces your username to be lowercase (steamerzone)
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
        env:
          IMAGE_REPOSITORY: ${{ text.lowercase(github.repository) }}
